-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity receive is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_gmii_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    s_gmii_V_empty_n : IN STD_LOGIC;
    s_gmii_V_read : OUT STD_LOGIC;
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axis_TVALID : OUT STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC;
    m_axis_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    rx_status : OUT STD_LOGIC_VECTOR (22 downto 0);
    rx_status_ap_vld : OUT STD_LOGIC );
end;


architecture behav of receive is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "receive,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325tffg900-2,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=13.570000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=145,HLS_SYN_LUT=901}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_D5 : STD_LOGIC_VECTOR (7 downto 0) := "11010101";
    constant ap_const_lv16_E : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001110";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_C : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001100";
    constant ap_const_lv16_D : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_EDB88320 : STD_LOGIC_VECTOR (31 downto 0) := "11101101101110001000001100100000";
    constant ap_const_lv32_DEBB20E3 : STD_LOGIC_VECTOR (31 downto 0) := "11011110101110110010000011100011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_5DC : STD_LOGIC_VECTOR (15 downto 0) := "0000010111011100";
    constant ap_const_lv16_5DD : STD_LOGIC_VECTOR (15 downto 0) := "0000010111011101";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal frm_cnt_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal crc_state_V : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    signal len_type_V : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    signal usr_cnt_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cur_rxd_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal cur_dv_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal data_err : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pipeline_Array_rxd_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal pipeline_Array_rxd_V_ce0 : STD_LOGIC;
    signal pipeline_Array_rxd_V_we0 : STD_LOGIC;
    signal pipeline_Array_rxd_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal pipeline_Array_rxd_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal pipeline_Array_dv_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal pipeline_Array_dv_V_ce0 : STD_LOGIC;
    signal pipeline_Array_dv_V_we0 : STD_LOGIC;
    signal pipeline_Array_dv_V_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal pipeline_Array_dv_V_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal pipeline_Array_er_V_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_262_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_n_reg_1009 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_73 : BOOLEAN;
    signal or_cond_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_83 : BOOLEAN;
    signal empty_n_2_reg_1017 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_n_1_reg_1021 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_270_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_556_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_reg_1048 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_bdd_100 : BOOLEAN;
    signal tmp_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal din_1_phi_fu_206_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_ioackin_m_axis_TREADY : STD_LOGIC;
    signal empty_n_3_reg_1055 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1067 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_286_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_2_reg_223 : STD_LOGIC_VECTOR (7 downto 0);
    signal last_0_s_reg_181 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_bdd_144 : BOOLEAN;
    signal last_0_1_reg_193 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_data_V_2_phi_fu_229_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_1_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_en_reg_212 : STD_LOGIC_VECTOR (1 downto 0);
    signal output_en_3_phi_fu_247_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_nbread_fu_152_p2_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_8_i_fu_836_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_518_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_1_fu_542_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_474_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_490_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal DataOut_rxd_V_2_fu_396_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal DataOut_rxd_V_1_fu_416_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal DataOut_rxd_V_3_fu_852_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal DataOut_rxd_V_4_fu_993_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_fu_982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ioackin_m_axis_TREADY : STD_LOGIC := '0';
    signal ap_reg_ioackin_rx_status_dummy_ack : STD_LOGIC := '0';
    signal din_rxd_V_fu_356_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_rxd_V_2_fu_392_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_rxd_V_1_fu_412_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_rxd_V_3_fu_848_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_rxd_V_4_fu_989_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal phitmp_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_cast_fu_454_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_cast_fu_464_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal r_V_1_fu_458_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_37_fu_514_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_532_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_572_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_7_fu_580_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_i_fu_590_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_38_fu_586_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_i_cast_cast_fu_604_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_600_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_i_fu_612_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_1_i_fu_622_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_39_fu_618_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_1_i_cast_cast_fu_636_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_632_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_i_fu_644_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_2_i_fu_654_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_40_fu_650_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_2_i_cast_cast_fu_668_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_664_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_2_i_fu_676_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_3_i_fu_686_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_41_fu_682_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_3_i_cast_cast_fu_700_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_696_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_3_i_fu_708_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_4_i_fu_718_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_42_fu_714_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_4_i_cast_cast_fu_732_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_728_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_4_i_fu_740_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_5_i_fu_750_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_43_fu_746_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_5_i_cast_cast_fu_764_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_760_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_i_fu_772_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_6_i_fu_782_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_44_fu_778_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_6_i_cast_cast_fu_796_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_26_fu_792_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_i_8_fu_804_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_6_7_i_fu_814_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_45_fu_810_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_7_7_i_cast_cast_fu_828_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_27_fu_824_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_49_fu_874_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_assign_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_933_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_941_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_51_fu_956_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_953_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_bdd_247 : BOOLEAN;
    signal ap_sig_bdd_88 : BOOLEAN;
    signal ap_sig_bdd_91 : BOOLEAN;
    signal ap_sig_bdd_126 : BOOLEAN;
    signal ap_sig_bdd_204 : BOOLEAN;
    signal ap_sig_bdd_744 : BOOLEAN;

    component receive_pipeline_Array_rxd_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component receive_pipeline_Array_dv_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    pipeline_Array_rxd_V_U : component receive_pipeline_Array_rxd_V
    generic map (
        DataWidth => 8,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => pipeline_Array_rxd_V_address0,
        ce0 => pipeline_Array_rxd_V_ce0,
        we0 => pipeline_Array_rxd_V_we0,
        d0 => pipeline_Array_rxd_V_d0,
        q0 => pipeline_Array_rxd_V_q0);

    pipeline_Array_dv_V_U : component receive_pipeline_Array_dv_V
    generic map (
        DataWidth => 1,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => pipeline_Array_dv_V_address0,
        ce0 => pipeline_Array_dv_V_ce0,
        we0 => pipeline_Array_dv_V_we0,
        d0 => pipeline_Array_dv_V_d0,
        q0 => pipeline_Array_dv_V_q0);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_m_axis_TREADY assign process. --
    ap_reg_ioackin_m_axis_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_m_axis_TREADY <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2)))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2)))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))))) then 
                    ap_reg_ioackin_m_axis_TREADY <= ap_const_logic_0;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_1 = m_axis_TREADY)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2)) and (ap_const_logic_1 = m_axis_TREADY)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and (ap_const_logic_1 = m_axis_TREADY)))) then 
                    ap_reg_ioackin_m_axis_TREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_rx_status_dummy_ack assign process. --
    ap_reg_ioackin_rx_status_dummy_ack_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_rx_status_dummy_ack <= ap_const_logic_0;
            else
                if (ap_sig_bdd_247) then
                    if (not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) then 
                        ap_reg_ioackin_rx_status_dummy_ack <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = ap_const_logic_1)) then 
                        ap_reg_ioackin_rx_status_dummy_ack <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- crc_state_V assign process. --
    crc_state_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))))) then 
                crc_state_V <= r_V_8_i_fu_836_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                crc_state_V <= ap_const_lv32_FFFFFFFF;
            end if; 
        end if;
    end process;

    -- cur_rxd_V assign process. --
    cur_rxd_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not((ap_const_lv1_0 = grp_fu_262_p1))) then
                if (ap_sig_bdd_204) then 
                    cur_rxd_V <= DataOut_rxd_V_4_fu_993_p4;
                elsif (ap_sig_bdd_126) then 
                    cur_rxd_V <= DataOut_rxd_V_3_fu_852_p4;
                elsif (ap_sig_bdd_91) then 
                    cur_rxd_V <= DataOut_rxd_V_1_fu_416_p4;
                elsif (ap_sig_bdd_88) then 
                    cur_rxd_V <= DataOut_rxd_V_2_fu_396_p4;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                    cur_rxd_V <= pipeline_Array_rxd_V_q0;
                end if;
            end if; 
        end if;
    end process;

    -- data_err assign process. --
    data_err_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    -- frm_cnt_V assign process. --
    frm_cnt_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))))) then 
                frm_cnt_V <= tmp_8_fu_556_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                frm_cnt_V <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    -- last_0_1_reg_193 assign process. --
    last_0_1_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not((ap_const_lv1_0 = grp_fu_262_p1))) then
                if (ap_sig_bdd_744) then 
                    last_0_1_reg_193 <= tmp_data_V_2_phi_fu_229_p8;
                elsif (ap_sig_bdd_91) then 
                    last_0_1_reg_193 <= last_0_s_reg_181;
                end if;
            end if; 
        end if;
    end process;

    -- len_type_V assign process. --
    len_type_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = tmp_2_fu_502_p2)))) then 
                len_type_V <= p_1_fu_542_p3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and (ap_const_lv1_0 = tmp_2_fu_502_p2) and not((ap_const_lv1_0 = tmp_4_fu_508_p2)))) then 
                len_type_V <= r_V_fu_518_p3;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                len_type_V <= ap_const_lv16_FFFF;
            end if; 
        end if;
    end process;

    -- output_en_reg_212 assign process. --
    output_en_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not((ap_const_lv1_0 = grp_fu_262_p1))) then
                if (ap_sig_bdd_744) then 
                    output_en_reg_212 <= output_en_3_phi_fu_247_p8;
                elsif (ap_sig_bdd_91) then 
                    output_en_reg_212 <= ap_const_lv2_1;
                end if;
            end if; 
        end if;
    end process;

    -- tmp_data_V_2_reg_223 assign process. --
    tmp_data_V_2_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and (((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = din_1_phi_fu_206_p4)) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = tmp_7_fu_448_p2))) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
                tmp_data_V_2_reg_223 <= cur_rxd_V;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2)))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = tmp_3_fu_442_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2)))))))) then 
                tmp_data_V_2_reg_223 <= last_0_1_reg_193;
            end if; 
        end if;
    end process;

    -- usr_cnt_V assign process. --
    usr_cnt_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and (((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = din_1_phi_fu_206_p4)) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = tmp_7_fu_448_p2))) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
                usr_cnt_V <= tmp_6_fu_490_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))))) then 
                usr_cnt_V <= tmp_5_fu_474_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                usr_cnt_V <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1))))) then
                cur_dv_V <= pipeline_Array_dv_V_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1)) and not((ap_const_lv1_0 = grp_fu_286_p4))))) then
                din_1_reg_203 <= s_gmii_V_dout(8 downto 8);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)))) then
                empty_n_1_reg_1021 <= grp_nbread_fu_152_p2_0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2))) then
                empty_n_2_reg_1017 <= grp_nbread_fu_152_p2_0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))))) then
                empty_n_3_reg_1055 <= grp_nbread_fu_152_p2_0;
                tmp_8_reg_1048 <= tmp_8_fu_556_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                empty_n_reg_1009 <= grp_nbread_fu_152_p2_0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))))) then
                last_0_s_reg_181 <= tmp_data_V_2_reg_223;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                or_cond_reg_1013 <= or_cond_fu_386_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_lv1_0 = grp_fu_286_p4))) then
                tmp_9_reg_1067 <= tmp_9_fu_868_p2;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (grp_fu_262_p1, empty_n_reg_1009, ap_CS_fsm, or_cond_fu_386_p2, or_cond_reg_1013, empty_n_2_reg_1017, empty_n_1_reg_1021, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, grp_fu_286_p4)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when ap_ST_st2_fsm_1 => 
                if (not((ap_const_lv1_0 = grp_fu_262_p1))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                end if;
            when ap_ST_st3_fsm_2 => 
                if ((not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1)))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                elsif (((ap_const_lv1_0 = or_cond_fu_386_p2) and not((ap_const_lv1_0 = grp_fu_262_p1)))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                end if;
            when ap_ST_st4_fsm_3 => 
                if ((not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1)) and not((ap_const_lv1_0 = grp_fu_286_p4)))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                elsif ((not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and ((ap_const_lv1_0 = grp_fu_262_p1) or (ap_const_lv1_0 = grp_fu_286_p4)))) then
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                end if;
            when ap_ST_st5_fsm_4 => 
                if ((not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))) and ((ap_const_lv1_0 = empty_n_reg_1009) or ((ap_const_lv1_0 = or_cond_reg_1013) and (ap_const_lv1_0 = empty_n_2_reg_1017)) or (not((ap_const_lv1_0 = or_cond_reg_1013)) and (ap_const_lv1_0 = empty_n_1_reg_1021)) or (not((ap_const_lv1_0 = or_cond_reg_1013)) and (ap_const_lv1_0 = empty_n_3_reg_1055)) or ((ap_const_lv1_0 = grp_fu_262_p1) and not((ap_const_lv1_0 = or_cond_reg_1013)))))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                elsif ((not((ap_const_lv1_0 = grp_fu_262_p1)) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    DataOut_rxd_V_1_fu_416_p4 <= pipeline_Array_rxd_V_q0;
    DataOut_rxd_V_2_fu_396_p4 <= pipeline_Array_rxd_V_q0;
    DataOut_rxd_V_3_fu_852_p4 <= pipeline_Array_rxd_V_q0;
    DataOut_rxd_V_4_fu_993_p4 <= pipeline_Array_rxd_V_q0;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    -- ap_sig_bdd_100 assign process. --
    ap_sig_bdd_100_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_100 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    -- ap_sig_bdd_126 assign process. --
    ap_sig_bdd_126_assign_proc : process(ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY)
    begin
                ap_sig_bdd_126 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))));
    end process;


    -- ap_sig_bdd_144 assign process. --
    ap_sig_bdd_144_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_144 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    -- ap_sig_bdd_204 assign process. --
    ap_sig_bdd_204_assign_proc : process(empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
                ap_sig_bdd_204 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))));
    end process;


    -- ap_sig_bdd_247 assign process. --
    ap_sig_bdd_247_assign_proc : process(empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
                ap_sig_bdd_247 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)));
    end process;


    -- ap_sig_bdd_73 assign process. --
    ap_sig_bdd_73_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_73 <= (ap_CS_fsm(1 downto 1) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_744 assign process. --
    ap_sig_bdd_744_assign_proc : process(ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, grp_fu_286_p4)
    begin
                ap_sig_bdd_744 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_286_p4)));
    end process;


    -- ap_sig_bdd_83 assign process. --
    ap_sig_bdd_83_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_83 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_88 assign process. --
    ap_sig_bdd_88_assign_proc : process(or_cond_fu_386_p2, ap_sig_cseq_ST_st3_fsm_2)
    begin
                ap_sig_bdd_88 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2));
    end process;


    -- ap_sig_bdd_91 assign process. --
    ap_sig_bdd_91_assign_proc : process(or_cond_fu_386_p2, ap_sig_cseq_ST_st3_fsm_2)
    begin
                ap_sig_bdd_91 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)));
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_73)
    begin
        if (ap_sig_bdd_73) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st3_fsm_2 assign process. --
    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_bdd_83)
    begin
        if (ap_sig_bdd_83) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st4_fsm_3 assign process. --
    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_bdd_100)
    begin
        if (ap_sig_bdd_100) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st5_fsm_4 assign process. --
    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_bdd_144)
    begin
        if (ap_sig_bdd_144) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ioackin_m_axis_TREADY assign process. --
    ap_sig_ioackin_m_axis_TREADY_assign_proc : process(m_axis_TREADY, ap_reg_ioackin_m_axis_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_m_axis_TREADY)) then 
            ap_sig_ioackin_m_axis_TREADY <= m_axis_TREADY;
        else 
            ap_sig_ioackin_m_axis_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    din_1_phi_fu_206_p4 <= din_1_reg_203;
    din_rxd_V_1_fu_412_p1 <= s_gmii_V_dout(8 - 1 downto 0);
    din_rxd_V_2_fu_392_p1 <= s_gmii_V_dout(8 - 1 downto 0);
    din_rxd_V_3_fu_848_p1 <= s_gmii_V_dout(8 - 1 downto 0);
    din_rxd_V_4_fu_989_p1 <= s_gmii_V_dout(8 - 1 downto 0);
    din_rxd_V_fu_356_p1 <= s_gmii_V_dout(8 - 1 downto 0);
    grp_fu_262_p1 <= (0=>s_gmii_V_empty_n, others=>'-');
    grp_fu_270_p3 <= s_gmii_V_dout(8 downto 8);
    grp_fu_286_p4 <= pipeline_Array_dv_V_q0;
    grp_nbread_fu_152_p2_0 <= (0=>s_gmii_V_empty_n, others=>'-');
    icmp_fu_883_p2 <= "1" when (tmp_49_fu_874_p4 = ap_const_lv10_0) else "0";
    lhs_V_cast_fu_454_p1 <= std_logic_vector(resize(unsigned(len_type_V),17));

    -- m_axis_TDATA assign process. --
    m_axis_TDATA_assign_proc : process(cur_rxd_V, empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, empty_n_3_reg_1055, tmp_data_V_2_reg_223, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))) then 
            m_axis_TDATA <= tmp_data_V_2_reg_223;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            m_axis_TDATA <= cur_rxd_V;
        else 
            m_axis_TDATA <= "XXXXXXXX";
        end if; 
    end process;


    -- m_axis_TLAST assign process. --
    m_axis_TLAST_assign_proc : process(empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))) then 
            m_axis_TLAST <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            m_axis_TLAST <= ap_const_lv1_0;
        else 
            m_axis_TLAST <= "X";
        end if; 
    end process;


    -- m_axis_TUSER assign process. --
    m_axis_TUSER_assign_proc : process(empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4, tmp_user_V_fu_982_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)))) then 
            m_axis_TUSER <= tmp_user_V_fu_982_p2;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            m_axis_TUSER <= ap_const_lv1_0;
        else 
            m_axis_TUSER <= "X";
        end if; 
    end process;


    -- m_axis_TVALID assign process. --
    m_axis_TVALID_assign_proc : process(empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4, ap_reg_ioackin_m_axis_TREADY)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_reg_ioackin_m_axis_TREADY)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2)) and (ap_const_logic_0 = ap_reg_ioackin_m_axis_TREADY)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and (ap_const_logic_0 = ap_reg_ioackin_m_axis_TREADY)))) then 
            m_axis_TVALID <= ap_const_logic_1;
        else 
            m_axis_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_cond_fu_386_p2 <= (cur_dv_V and phitmp_fu_380_p2);

    -- output_en_3_phi_fu_247_p8 assign process. --
    output_en_3_phi_fu_247_p8_assign_proc : process(ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, output_en_reg_212)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = din_1_phi_fu_206_p4)) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = tmp_7_fu_448_p2))) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            output_en_3_phi_fu_247_p8 <= ap_const_lv2_0;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and not((ap_const_lv1_0 = tmp_3_fu_442_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            output_en_3_phi_fu_247_p8 <= output_en_reg_212;
        else 
            output_en_3_phi_fu_247_p8 <= "XX";
        end if; 
    end process;

    p_1_fu_542_p3 <= (tmp_15_fu_532_p4 & cur_rxd_V);
    phitmp_fu_380_p2 <= "1" when (cur_rxd_V = ap_const_lv8_D5) else "0";
    pipeline_Array_dv_V_address0 <= ap_const_lv3_4;

    -- pipeline_Array_dv_V_ce0 assign process. --
    pipeline_Array_dv_V_ce0_assign_proc : process(grp_fu_262_p1, empty_n_reg_1009, ap_sig_cseq_ST_st2_fsm_1, or_cond_fu_386_p2, or_cond_reg_1013, ap_sig_cseq_ST_st3_fsm_2, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1))))) then 
            pipeline_Array_dv_V_ce0 <= ap_const_logic_1;
        else 
            pipeline_Array_dv_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pipeline_Array_dv_V_d0 <= grp_fu_270_p3;

    -- pipeline_Array_dv_V_we0 assign process. --
    pipeline_Array_dv_V_we0_assign_proc : process(grp_fu_262_p1, empty_n_reg_1009, ap_sig_cseq_ST_st2_fsm_1, or_cond_fu_386_p2, or_cond_reg_1013, ap_sig_cseq_ST_st3_fsm_2, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1))))) then 
            pipeline_Array_dv_V_we0 <= ap_const_logic_1;
        else 
            pipeline_Array_dv_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    pipeline_Array_rxd_V_address0 <= ap_const_lv3_4;

    -- pipeline_Array_rxd_V_ce0 assign process. --
    pipeline_Array_rxd_V_ce0_assign_proc : process(grp_fu_262_p1, empty_n_reg_1009, ap_sig_cseq_ST_st2_fsm_1, or_cond_fu_386_p2, or_cond_reg_1013, ap_sig_cseq_ST_st3_fsm_2, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1))))) then 
            pipeline_Array_rxd_V_ce0 <= ap_const_logic_1;
        else 
            pipeline_Array_rxd_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- pipeline_Array_rxd_V_d0 assign process. --
    pipeline_Array_rxd_V_d0_assign_proc : process(grp_fu_262_p1, ap_sig_cseq_ST_st2_fsm_1, din_rxd_V_fu_356_p1, din_rxd_V_2_fu_392_p1, din_rxd_V_1_fu_412_p1, din_rxd_V_3_fu_848_p1, din_rxd_V_4_fu_989_p1, ap_sig_bdd_88, ap_sig_bdd_91, ap_sig_bdd_126, ap_sig_bdd_204)
    begin
        if (not((ap_const_lv1_0 = grp_fu_262_p1))) then
            if (ap_sig_bdd_204) then 
                pipeline_Array_rxd_V_d0 <= din_rxd_V_4_fu_989_p1;
            elsif (ap_sig_bdd_126) then 
                pipeline_Array_rxd_V_d0 <= din_rxd_V_3_fu_848_p1;
            elsif (ap_sig_bdd_91) then 
                pipeline_Array_rxd_V_d0 <= din_rxd_V_1_fu_412_p1;
            elsif (ap_sig_bdd_88) then 
                pipeline_Array_rxd_V_d0 <= din_rxd_V_2_fu_392_p1;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
                pipeline_Array_rxd_V_d0 <= din_rxd_V_fu_356_p1;
            else 
                pipeline_Array_rxd_V_d0 <= "XXXXXXXX";
            end if;
        else 
            pipeline_Array_rxd_V_d0 <= "XXXXXXXX";
        end if; 
    end process;


    -- pipeline_Array_rxd_V_we0 assign process. --
    pipeline_Array_rxd_V_we0_assign_proc : process(grp_fu_262_p1, empty_n_reg_1009, ap_sig_cseq_ST_st2_fsm_1, or_cond_fu_386_p2, or_cond_reg_1013, ap_sig_cseq_ST_st3_fsm_2, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((not((ap_const_lv1_0 = grp_fu_262_p1)) and (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2)) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2) and not((ap_const_lv1_0 = grp_fu_262_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2))))) and not((ap_const_lv1_0 = grp_fu_262_p1))))) then 
            pipeline_Array_rxd_V_we0 <= ap_const_logic_1;
        else 
            pipeline_Array_rxd_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_458_p2 <= std_logic_vector(unsigned(lhs_V_cast_fu_454_p1) + unsigned(ap_const_lv17_1FFFF));
    r_V_1_i_fu_644_p2 <= (r_V_7_1_i_cast_cast_fu_636_p3 xor tmp_19_fu_632_p1);
    r_V_2_i_fu_676_p2 <= (r_V_7_2_i_cast_cast_fu_668_p3 xor tmp_20_fu_664_p1);
    r_V_3_i_fu_708_p2 <= (r_V_7_3_i_cast_cast_fu_700_p3 xor tmp_21_fu_696_p1);
    r_V_4_i_fu_740_p2 <= (r_V_7_4_i_cast_cast_fu_732_p3 xor tmp_24_fu_728_p1);
    r_V_5_i_fu_772_p2 <= (r_V_7_5_i_cast_cast_fu_764_p3 xor tmp_25_fu_760_p1);
    r_V_6_1_i_fu_622_p4 <= r_V_i_fu_612_p2(31 downto 1);
    r_V_6_2_i_fu_654_p4 <= r_V_1_i_fu_644_p2(31 downto 1);
    r_V_6_3_i_fu_686_p4 <= r_V_2_i_fu_676_p2(31 downto 1);
    r_V_6_4_i_fu_718_p4 <= r_V_3_i_fu_708_p2(31 downto 1);
    r_V_6_5_i_fu_750_p4 <= r_V_4_i_fu_740_p2(31 downto 1);
    r_V_6_6_i_fu_782_p4 <= r_V_5_i_fu_772_p2(31 downto 1);
    r_V_6_7_i_fu_814_p4 <= r_V_i_8_fu_804_p2(31 downto 1);
    r_V_6_i_fu_590_p4 <= tmp_i_7_fu_580_p2(31 downto 1);
    r_V_7_1_i_cast_cast_fu_636_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_39_fu_618_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_2_i_cast_cast_fu_668_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_40_fu_650_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_3_i_cast_cast_fu_700_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_41_fu_682_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_4_i_cast_cast_fu_732_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_42_fu_714_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_5_i_cast_cast_fu_764_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_43_fu_746_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_6_i_cast_cast_fu_796_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_44_fu_778_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_7_i_cast_cast_fu_828_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_45_fu_810_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_7_i_cast_cast_fu_604_p3 <= 
        ap_const_lv32_EDB88320 when (tmp_38_fu_586_p1(0) = '1') else 
        ap_const_lv32_0;
    r_V_8_i_fu_836_p2 <= (r_V_7_7_i_cast_cast_fu_828_p3 xor tmp_27_fu_824_p1);
    r_V_fu_518_p3 <= (tmp_37_fu_514_p1 & cur_rxd_V);
    r_V_i_8_fu_804_p2 <= (r_V_7_6_i_cast_cast_fu_796_p3 xor tmp_26_fu_792_p1);
    r_V_i_fu_612_p2 <= (r_V_7_i_cast_cast_fu_604_p3 xor tmp_16_fu_600_p1);
    rx_status <= ((((((((tmp_11_fu_889_p2 & ap_const_lv1_0) & tmp_51_fu_956_p1) & tmp_9_reg_1067) & val_assign_fu_906_p2) & icmp_fu_883_p2) & ap_const_lv2_0) & tmp_18_fu_947_p2) & tmp_50_fu_953_p1);

    -- rx_status_ap_vld assign process. --
    rx_status_ap_vld_assign_proc : process(empty_n_reg_1009, or_cond_reg_1013, empty_n_1_reg_1021, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4, ap_reg_ioackin_rx_status_dummy_ack)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and (ap_const_logic_0 = ap_reg_ioackin_rx_status_dummy_ack))) then 
            rx_status_ap_vld <= ap_const_logic_1;
        else 
            rx_status_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    -- s_gmii_V_read assign process. --
    s_gmii_V_read_assign_proc : process(s_gmii_V_empty_n, empty_n_reg_1009, ap_sig_cseq_ST_st2_fsm_1, or_cond_fu_386_p2, or_cond_reg_1013, ap_sig_cseq_ST_st3_fsm_2, empty_n_1_reg_1021, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, ap_sig_ioackin_m_axis_TREADY, empty_n_3_reg_1055, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((ap_const_logic_1 = s_gmii_V_empty_n) and (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055)) and not(((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = empty_n_reg_1009)) and not((ap_const_lv1_0 = or_cond_reg_1013)) and not((ap_const_lv1_0 = empty_n_1_reg_1021)) and not((ap_const_lv1_0 = empty_n_3_reg_1055))))) or ((ap_const_logic_1 = s_gmii_V_empty_n) and (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2)) and (ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY)) or ((ap_const_logic_0 = ap_sig_ioackin_m_axis_TREADY) and not((ap_const_lv1_0 = tmp_fu_436_p2)))))) or ((ap_const_logic_1 = s_gmii_V_empty_n) and (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = or_cond_fu_386_p2))) or ((ap_const_logic_1 = s_gmii_V_empty_n) and (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = or_cond_fu_386_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_logic_1 = s_gmii_V_empty_n))))))))))) then 
            s_gmii_V_read <= ap_const_logic_1;
        else 
            s_gmii_V_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_916_p2 <= (tmp_9_reg_1067 or icmp_fu_883_p2);
    tmp3_fu_933_p3 <= (ap_const_lv31_0 & tmp_23_fu_927_p2);
    tmp_11_fu_889_p2 <= "1" when (unsigned(tmp_8_reg_1048) > unsigned(ap_const_lv16_5DC)) else "0";
    tmp_12_fu_894_p2 <= "1" when (unsigned(len_type_V) < unsigned(ap_const_lv16_5DD)) else "0";
    tmp_13_fu_900_p2 <= "0" when (len_type_V = usr_cnt_V) else "1";
    tmp_15_fu_532_p4 <= len_type_V(15 downto 8);
    tmp_16_fu_600_p1 <= std_logic_vector(resize(unsigned(r_V_6_i_fu_590_p4),32));
    tmp_17_fu_941_p2 <= (tmp3_fu_933_p3 or data_err);
    tmp_18_fu_947_p2 <= "1" when (tmp_17_fu_941_p2 = ap_const_lv32_0) else "0";
    tmp_19_fu_632_p1 <= std_logic_vector(resize(unsigned(r_V_6_1_i_fu_622_p4),32));
    tmp_1_fu_468_p2 <= "1" when (signed(tmp_cast_fu_464_p1) < signed(r_V_1_fu_458_p2)) else "0";
    tmp_20_fu_664_p1 <= std_logic_vector(resize(unsigned(r_V_6_2_i_fu_654_p4),32));
    tmp_21_fu_696_p1 <= std_logic_vector(resize(unsigned(r_V_6_3_i_fu_686_p4),32));
    tmp_22_fu_921_p2 <= (tmp1_fu_916_p2 or tmp_11_fu_889_p2);
    tmp_23_fu_927_p2 <= (tmp_22_fu_921_p2 or val_assign_fu_906_p2);
    tmp_24_fu_728_p1 <= std_logic_vector(resize(unsigned(r_V_6_4_i_fu_718_p4),32));
    tmp_25_fu_760_p1 <= std_logic_vector(resize(unsigned(r_V_6_5_i_fu_750_p4),32));
    tmp_26_fu_792_p1 <= std_logic_vector(resize(unsigned(r_V_6_6_i_fu_782_p4),32));
    tmp_27_fu_824_p1 <= std_logic_vector(resize(unsigned(r_V_6_7_i_fu_814_p4),32));
    tmp_2_fu_502_p2 <= "1" when (frm_cnt_V = ap_const_lv16_C) else "0";
    tmp_37_fu_514_p1 <= len_type_V(8 - 1 downto 0);
    tmp_38_fu_586_p1 <= tmp_i_7_fu_580_p2(1 - 1 downto 0);
    tmp_39_fu_618_p1 <= r_V_i_fu_612_p2(1 - 1 downto 0);
    tmp_3_fu_442_p2 <= "1" when (output_en_reg_212 = ap_const_lv2_0) else "0";
    tmp_40_fu_650_p1 <= r_V_1_i_fu_644_p2(1 - 1 downto 0);
    tmp_41_fu_682_p1 <= r_V_2_i_fu_676_p2(1 - 1 downto 0);
    tmp_42_fu_714_p1 <= r_V_3_i_fu_708_p2(1 - 1 downto 0);
    tmp_43_fu_746_p1 <= r_V_4_i_fu_740_p2(1 - 1 downto 0);
    tmp_44_fu_778_p1 <= r_V_5_i_fu_772_p2(1 - 1 downto 0);
    tmp_45_fu_810_p1 <= r_V_i_8_fu_804_p2(1 - 1 downto 0);
    tmp_49_fu_874_p4 <= tmp_8_reg_1048(15 downto 6);
    tmp_4_fu_508_p2 <= "1" when (frm_cnt_V = ap_const_lv16_D) else "0";
    tmp_50_fu_953_p1 <= tmp_8_reg_1048(14 - 1 downto 0);
    tmp_51_fu_956_p1 <= data_err(1 - 1 downto 0);
    tmp_5_fu_474_p2 <= std_logic_vector(unsigned(usr_cnt_V) + unsigned(ap_const_lv16_1));
    tmp_6_fu_490_p2 <= std_logic_vector(unsigned(usr_cnt_V) + unsigned(ap_const_lv16_1));
    tmp_7_fu_448_p2 <= "1" when (len_type_V = ap_const_lv16_0) else "0";
    tmp_8_fu_556_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(frm_cnt_V));
    tmp_9_fu_868_p2 <= "0" when (r_V_8_i_fu_836_p2 = ap_const_lv32_DEBB20E3) else "1";
    tmp_cast_fu_464_p1 <= std_logic_vector(resize(unsigned(usr_cnt_V),17));

    -- tmp_data_V_2_phi_fu_229_p8 assign process. --
    tmp_data_V_2_phi_fu_229_p8_assign_proc : process(cur_rxd_V, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_436_p2, tmp_3_fu_442_p2, din_1_phi_fu_206_p4, tmp_7_fu_448_p2, tmp_1_fu_468_p2, last_0_1_reg_193)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = din_1_phi_fu_206_p4)) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = tmp_7_fu_448_p2))) or ((ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and (ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            tmp_data_V_2_phi_fu_229_p8 <= cur_rxd_V;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_436_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and not((ap_const_lv1_0 = tmp_3_fu_442_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_436_p2) and (ap_const_lv1_0 = tmp_3_fu_442_p2) and not((ap_const_lv1_0 = din_1_phi_fu_206_p4)) and (ap_const_lv1_0 = tmp_7_fu_448_p2) and not((ap_const_lv1_0 = tmp_1_fu_468_p2))))) then 
            tmp_data_V_2_phi_fu_229_p8 <= last_0_1_reg_193;
        else 
            tmp_data_V_2_phi_fu_229_p8 <= "XXXXXXXX";
        end if; 
    end process;

    tmp_fu_436_p2 <= "1" when (unsigned(frm_cnt_V) < unsigned(ap_const_lv16_E)) else "0";
    tmp_i_7_fu_580_p2 <= (crc_state_V xor tmp_i_fu_572_p1);
    tmp_i_fu_572_p1 <= std_logic_vector(resize(unsigned(cur_rxd_V),32));
    tmp_user_V_fu_982_p2 <= (tmp_18_fu_947_p2 xor ap_const_lv1_1);
    val_assign_fu_906_p2 <= (tmp_12_fu_894_p2 and tmp_13_fu_900_p2);
end behav;
